### ISSUE TITLE
Crash Report

### ISSUE THREAD

**Issue by anexusarchon** [Chicken-Bones/EnderStorage#35]
Caused by attempting to look at an ender tank in creative tab. Also crashes when attempting to search for an ender tank in NEI:
http://pastebin.com/Uwq4dzSt

**Comment by spocane** [comment]
Seems to be with Forge 10.13.3.1355 - 10.13.3.1358. Seems that "1355" removed fluidID from ItemStack which i am guessing is causing the crashes!?

I got a similar crash report by having ender tanks in my inventory and the attached crash with placed ender tanks in the world. Removing enderstorage from the instance fixes the crash

http://pastebin.com/TVTyi0bw

**Comment by homemmakako** [comment]
I am having the same problem, but I'm using forge 10.13.3.1360. I don't know why but if you search for the item in Nei it will kick you from the server (even a single player one) and send you to the multiplayer menu. However if you search for the recipe of an ender tank you will crash and the same will happen if you open a world in which a tank has already been placed. I don't think it is a forge thing because I was having the same issue with older forge versions, but I am not a reliable person on the subject :stuck_out_tongue_winking_eye:

**Comment by Chicken-Bones** [comment]
Fixed by 13a79b080c47d070e2142f245043e28340bb1b62 (1.4.6.31)

**Comment by Tsunayoshi** [comment]
Thank you!!
