### ISSUE TITLE
[Suggestion] MySQL support?

### ISSUE THREAD

**Issue by LuxusDarkangel** [Chicken-Bones/EnderStorage#67]
Hi! I'm not sure if forge allows this, but implementing a mysql database to add suport for two servers using the same enderchest/endertank frequencies and content is viable?
This allows a bunch of possibilities, because right now because  you can't do it using a external software.

**Comment by Chicken-Bones** [comment]
There's no limitation in forge, but I don't think it's technically viable, due to the fact that every transaction (item add/remove) would have to be authenticated with the mysql server. This would take too long. It could be implemented for players accessing via the gui, because there is already async transaction support there, but machines expect a result instantly.

**Comment by LuxusDarkangel** [comment]
Saving the enderchest/endertank data in real time in the ES file and synchronizing this file with an external software would be viable? At least that way it can be synchronized at the cost of more hdd usage.

**Comment by Chicken-Bones** [comment]
Anyone is welcome to take a crack at it, but consider this:
What happens when two machines on two servers go to extract the same item at the same time?
Then repeat that 20 times. If that takes even a millisecond, the solution is not scalable.
